# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=b'files/', verbose_name=b'Document'),
        ),
    ]
