# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170215_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nb_views',
            field=models.IntegerField(default=0, verbose_name=b'Nombre de vues'),
        ),
    ]
